image:
  file: .gitpod.Dockerfile

github:
  prebuilds:    
    master: true    
    branches: true    
    pullRequests: true    
    pullRequestsFromForks: false    
    addCheck: true    
    addComment: false    
    addBadge: false

tasks:      
  - name: Workspace Initialization
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      # Initialize NPM for starting containers
      cd $THEIA_WORKSPACE_ROOT/backend-flask
      pip3 install -r requirements.txt
      cd $THEIA_WORKSPACE_ROOT/frontend-react-js
      npm i      
      cd $THEIA_WORKSPACE_ROOT
  
  - name: Docker Login
    command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

# Add VSCode Extensions
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - ms-azuretools.vscode-docker
    - ms-python.python
    - hashicorp.terraform
    - redhat.ansible
    - redhat.vscode-yaml
    - amazonwebservices.aws-toolkit-vscode
