image:
  file: .gitpod.Dockerfile

github:
  prebuilds:    
    master: true    
    branches: true    
    pullRequests: true    
    pullRequestsFromForks: false    
    addCheck: true    
    addComment: false    
    addBadge: false

tasks:
      
  - name: Workspace Initialization
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |

      # Initialize NPM for starting containers
      cd $THEIA_WORKSPACE_ROOT/aws-bootcamp-cruddur-2023/backend-flask
      pip3 install -r requirements.txt
      cd $THEIA_WORKSPACE_ROOT/aws-bootcamp-cruddur-2023/frontend-react-js
      npm i

      # Back to main directory
      cd $THEIA_WORKSPACE_ROOT

# Add VSCode Extensions
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - ms-azuretools.vscode-docker
    - ms-python.python
    - hashicorp.terraform
    - redhat.ansible
    - amazonwebservices.aws-toolkit-vscode
